intel/ros_openvino_toolkit

README.md, doc/BINARY_VERSION_README.md, doc/OPEN_SOURCE_CODE_README.md, script/environment_setup.sh, script/environment_setup_binary.sh
Only 2018 R3 is supported currently
=> update README for OpenVINO version information

sample/src/sample_pipeline_object.cpp
Fixed object detection to select CPU/GPU engine
=> Fix running object detection on GPU

doc/OPEN_SOURCE_CODE_README.md, dynamic_vino_lib/include/dynamic_vino_lib/factory.h, dynamic_vino_lib/src/factory.cpp, sample/src/sample_pipeline_object.cpp, sample/src/sample_pipeline_people.cpp, script/environment_setup.sh
add support for OpenVINO 2018_R4
=> Update OpenVINO R4 support

dynamic_vino_lib/src/outputs/base_output.cpp, dynamic_vino_lib/src/pipeline.cpp, sample/src/sample_pipeline_object.cpp, sample/src/sample_pipeline_people.cpp
=> add support for RealSense topic input

sample/src/sample_pipeline_object.cpp, sample/src/sample_pipeline_people.cpp
=> fix exit issue with "CTRL+C"

doc/BINARY_VERSION_README.md, doc/OPEN_SOURCE_CODE_README.md, script/environment_setup.sh, script/environment_setup_binary.sh
=> add warnings for installation script when removing files

README.md
=> update link address for master branch

dynamic_vino_lib/CMakeLists.txt, dynamic_vino_lib/include/dynamic_vino_lib/inputs/standard_camera.h, dynamic_vino_lib/include/dynamic_vino_lib/models/attributes/base_attribute.h, dynamic_vino_lib/include/dynamic_vino_lib/models/base_model.h, dynamic_vino_lib/include/dynamic_vino_lib/outputs/base_output.h, dynamic_vino_lib/include/dynamic_vino_lib/outputs/ros_service_output.h, dynamic_vino_lib/include/dynamic_vino_lib/services/frame_processing_server.h, dynamic_vino_lib/include/dynamic_vino_lib/services/pipeline_processing_server.h, dynamic_vino_lib/include/dynamic_vino_lib/utils/version_info.hpp, dynamic_vino_lib/src/services/frame_processing_server.cpp, dynamic_vino_lib/src/services/pipeline_processing_server.cpp, pipeline_srv_msgs/CMakeLists.txt, vino_launch/CMakeLists.txt
=> fix some build errors.

dynamic_vino_lib/include/dynamic_vino_lib/slog.h
fix for [issue#89](https://github.com/intel/ros_openvino_toolkit/issues/89)
=> update slog to fix slog errors for slog::debug

README.md, dynamic_vino_lib/include/dynamic_vino_lib/inferences/face_detection.h, dynamic_vino_lib/include/dynamic_vino_lib/inferences/person_reidentification.h, dynamic_vino_lib/include/dynamic_vino_lib/inputs/image_topic.h, dynamic_vino_lib/include/dynamic_vino_lib/inputs/realsense_camera_topic.h, dynamic_vino_lib/include/dynamic_vino_lib/outputs/base_output.h, dynamic_vino_lib/include/dynamic_vino_lib/outputs/ros_service_output.h, dynamic_vino_lib/include/dynamic_vino_lib/pipeline.h, dynamic_vino_lib/include/dynamic_vino_lib/utils/mutex_counter.hpp, dynamic_vino_lib/src/inputs/image_topic.cpp, dynamic_vino_lib/src/outputs/ros_service_output.cpp, dynamic_vino_lib/src/services/frame_processing_server.cpp, sample/src/image_object_client.cpp, sample/src/image_object_server.cpp
There are bug lists and solutions:
> **Solution**: `ObjectDetectionResult` is a class which is declared in `object_detection.h`,so I've included a head file named `object_detection.h` in `face_detection.h`
```c++
#include "dynamic_vino_lib/inferences/object_detection.h"
```
> **Solution**:  Include missing header in `person_reidentification.h`, 'Tracker' is a class which is declared in base_reidentification.h.
``` c++
#include "dynamic_vino_lib/inferences/base_reidentification.h"
```
> **Solution**: I've checked the `DetectObjectResponse.h` file which is in `devel/include/object_msgs/DetectObjectResponse.h`. 
It seems that `DetectObjectSrvResponse` is not correct at all because of there is not a class named as this, may be `DetectObjectRequest` is correct. So I've modified the file named …
=> Fix some bugs

dynamic_vino_lib/CMakeLists.txt, dynamic_vino_lib/include/dynamic_vino_lib/inputs/image_topic.h, dynamic_vino_lib/include/dynamic_vino_lib/outputs/base_output.h, dynamic_vino_lib/include/dynamic_vino_lib/outputs/image_window_output.h, dynamic_vino_lib/include/dynamic_vino_lib/utils/mutex_counter.hpp, dynamic_vino_lib/src/inputs/image_topic.cpp, dynamic_vino_lib/src/services/frame_processing_server.cpp
1. Modified `image_topic.cpp` and `image_topic.h` to fix ROS 1. 
2. Modified `dynamic_vino_lib/CMakeLists.txt` to add dependencies of `object_msgs`, which can decrease the number of error messages like ` ' fatal error: object_msgs/Object.h: No such file or directory  #include <object_msgs/Object.h>'`
=> Modified image_topic to fix ROS 1

dynamic_vino_lib/include/dynamic_vino_lib/outputs/base_output.h, dynamic_vino_lib/src/services/frame_processing_server.cpp
1. include related service response header files used by base_output.h
2. typo fix: DetectObjectRequest => DetectObjectResponse
@LewisLiuPub
=> BugFix: base_output.h

dynamic_vino_lib/CMakeLists.txt, sample/CMakeLists.txt
**Does this PR introduce a breaking change?**
=> fix#109 Remove dependencies of libcpu_extension.so [#109]

dynamic_vino_lib/include/dynamic_vino_lib/outputs/ros_topic_output.h, dynamic_vino_lib/src/outputs/ros_topic_output.cpp, people_msgs/CMakeLists.txt, people_msgs/msg/Landmark.msg, people_msgs/msg/LandmarkStamped.msg
=> Add Landmark message type and implement related API [issue#111]

README.md, dynamic_vino_lib/src/outputs/ros_topic_output.cpp
fix #114
**Does this PR introduce a breaking change?**
=> Bugfix: The message has prefix 'msg::' which is not correct for ROS1. [issue#114]

README.md, dynamic_vino_lib/CMakeLists.txt, dynamic_vino_lib/src/outputs/ros_topic_output.cpp, dynamic_vino_lib/src/pipeline_manager.cpp
fix #116
**Does this PR introduce a breaking change?**
=> Skip compile for 3 modules [issue#116]

dynamic_vino_lib/src/outputs/ros_topic_output.cpp, dynamic_vino_lib/src/outputs/rviz_output.cpp
fix #122
**Does this PR introduce a breaking change?**
=> define function getHeader() [#issue122]

dynamic_vino_lib/include/dynamic_vino_lib/outputs/ros_topic_output.h, dynamic_vino_lib/src/outputs/ros_service_output.cpp, dynamic_vino_lib/src/outputs/ros_topic_output.cpp
=> Comment 'segmented_object_topic_' which is not declared. [issue #128]

sample/src/pipeline_with_params.cpp
=> Remove incorrect header references [issue #132]

dynamic_vino_lib/include/dynamic_vino_lib/pipeline_manager.h, dynamic_vino_lib/src/pipeline_manager.cpp
fix #134
> I've tried to define function `createLandmarksDetection`, but it didn't work out (recorded in issue #134 )
=> Comment function 'createLandmarksDetection' related code [issue #134]

sample/src/image_object_client.cpp
=> Bug fix: srv.request.image_paths = image_path; [issue #138]

sample/src/image_object_server.cpp
=> Modified incorrect function name 'FrameProcessing' [issue #140]

dynamic_vino_lib/include/dynamic_vino_lib/pipeline_manager.h, dynamic_vino_lib/src/models/age_gender_detection_model.cpp, dynamic_vino_lib/src/models/emotion_detection_model.cpp, dynamic_vino_lib/src/outputs/image_window_output.cpp, dynamic_vino_lib/src/pipeline_manager.cpp, sample/CMakeLists.txt
fix #142
This pr was verified in virtual machine and build pass.
=> fixed some bugs for node launch well [issue #142]

.github/workflows/dev-ov_2020-3.yml, sample/package.xml
Signed-off-by: Lewis Liu <wei.zhi.liu@intel.com>
=> update sample package to version 0.9.0

dynamic_vino_lib/package.xml, people_msgs/package.xml, pipeline_srv_msgs/package.xml, vino_launch/package.xml, vino_param_lib/package.xml
Signed-off-by: Lewis Liu <wei.zhi.liu@intel.com>
=> update people_msgs package to version 0.9.0

dynamic_vino_lib/CMakeLists.txt, dynamic_vino_lib/include/dynamic_vino_lib/models/object_detection_ssd_model.h, dynamic_vino_lib/src/pipeline_manager.cpp
=> Enable object_detection_ssd_model [issue #147]

vino_param_lib/src/param_manager.cpp
Signed-off-by: Lewis Liu <wei.zhi.liu@intel.com>
=> fix instance error for base models

dynamic_vino_lib/CMakeLists.txt, dynamic_vino_lib/src/models/base_model.cpp, dynamic_vino_lib/src/pipeline.cpp, dynamic_vino_lib/src/pipeline_manager.cpp, vino_launch/launch/pipeline_object.launch, vino_launch/param/pipeline_object.yaml
Signed-off-by: Lewis Liu <wei.zhi.liu@intel.com>
=> enable Object Detection SSD models.

dynamic_vino_lib/src/models/object_segmentation_model.cpp, vino_launch/param/pipeline_reidentification.yaml
#161 
@caohuiyan
change `inputShapes.begin()->first` to `input_info_.begin()->first.c_str()`
=> change inputShapes.begin()->first to input_info_.begin()->first.c_str()

vino_launch/param/image_object_server.yaml, vino_launch/param/image_people_server.yaml, vino_launch/param/image_segmentation_server.yaml, vino_launch/param/multi_pipleine_service_object.yaml, vino_launch/param/pipeline_face_reidentification.yaml, vino_launch/param/pipeline_image.yaml, vino_launch/param/pipeline_object.yaml, vino_launch/param/pipeline_object_topic.yaml, vino_launch/param/pipeline_people.yaml, vino_launch/param/pipeline_reidentification.yaml, vino_launch/param/pipeline_segmentation.yaml, vino_launch/param/pipeline_vehicle_detection.yaml, vino_launch/param/pipeline_video.yaml
change model path `/opt/ros_openvino_toolkit` to `/opt/openvino_toolkit`
=> change model path `/opt/ros_openvino_toolkit` to `/opt/openvino_toolkit`

dynamic_vino_lib/CMakeLists.txt, dynamic_vino_lib/include/dynamic_vino_lib/models/face_reidentification_model.h, dynamic_vino_lib/include/dynamic_vino_lib/models/landmarks_detection_model.h, dynamic_vino_lib/include/dynamic_vino_lib/pipeline_manager.h, dynamic_vino_lib/src/models/face_reidentification_model.cpp, dynamic_vino_lib/src/models/landmarks_detection_model.cpp, dynamic_vino_lib/src/pipeline_manager.cpp, vino_launch/param/pipeline_face_reidentification.yaml, vino_launch/param/pipeline_reidentification.yaml
=> Enable landmark detection and face reidentification

dynamic_vino_lib/src/models/landmarks_detection_model.cpp
=> Add judgement for the type of input layer layout in landmark detection model [issue #168]

dynamic_vino_lib/src/outputs/image_window_output.cpp
=> remove cv::Rect in `object_segmentation`

dynamic_vino_lib/CMakeLists.txt, dynamic_vino_lib/include/dynamic_vino_lib/inputs/image_topic.h, dynamic_vino_lib/include/dynamic_vino_lib/inputs/ip_camera.h, dynamic_vino_lib/include/dynamic_vino_lib/pipeline_params.h, dynamic_vino_lib/src/inputs/image_topic.cpp, dynamic_vino_lib/src/inputs/ip_camera.cpp, dynamic_vino_lib/src/pipeline_manager.cpp, vino_launch/launch/pipeline_object_topic.launch, vino_launch/param/pipeline_object_topic.yaml
=> Add input support for `image_topic` and `ip_camera` [#iss173]

doc/ZH-CN/1. ros_openvino_runtime使用指南.md
update dev-2021.4 ReadMe File(ros_openvino_runtime使用指南.md)
1. Update install openvino2021.4 LTS
2. Run Demo
=> Update 1. ros_openvino_runtime使用指南.md

doc/quick_start/getting_started_with_Melodic_Ubuntu18.04.md, doc/quick_start/getting_started_with_Noetic_Ubuntu20.04.md, docker/ros_2021.4/ros_melodic/Dockerfile, docker/ros_2021.4/ros_melodic/docker_instraction.md, docker/ros_2021.4/ros_noetic/Dockerfile, docker/ros_2021.4/ros_noetic/docker_instraction.md
Doc(quick_start for melodic and noetic based on openvino 2021.4)  and Dockerfile(including build&launch instructions).
=> ros_ov toolkit master PR
